
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
models:
  - name: int_event_kpis
    description: Intermediate KPIs for events, aggregating from sales, attendees, and exhibitors.
    columns:
      - name: event_id
        description: Unique identifier for the event
      - name: avg_satisfaction
        description: Average attendee satisfaction score

        
